workflows:
  flutter-workflow:
    name: Build dyte_astrology
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      flutter: stable
      vars:
        # متغير API وهمي لتجنب خطأ padding
        DYTE_API_KEY: "DUMMY_API_KEY"
    scripts:
      - name: Navigate to project folder
        script: |
          cd sample/dyte_astrology
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
    artifacts:
      - sample/dyte_astrology/build/app/outputs/flutter-apk/app-release.apk
